---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  subway-{{ .Release.Namespace }}-rest-mapping
  labels:
    {{- include "subway.labels" . | nindent 4 }}
spec:
  host: {{ .Values.publicSubdomain }}.upchieve.org
  prefix: /
  timeout_ms: 500000
  resolver: endpoint
  load_balancer:
    policy: least_request
  service: "{{ include "subway.fullname" . }}-rest.{{ .Release.Namespace }}:{{ .Values.httpPort }}"
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  subway-{{ .Release.Namespace }}-whiteboard-reset-mapping
  labels:
    {{- include "subway.labels" . | nindent 4 }}
spec:
  host: {{ .Values.publicSubdomain }}.upchieve.org
  prefix: /whiteboard/reset/
  rewrite: /whiteboard/reset/
  timeout_ms: 500000
  resolver: endpoint
  load_balancer:
    policy: ring_hash
    source_ip: true
  service: "{{ include "subway.fullname" . }}-socket.{{ .Release.Namespace }}:{{ .Values.httpPort }}"
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  subway-{{ .Release.Namespace }}-whiteboard-mapping
  labels:
    {{- include "subway.labels" . | nindent 4 }}
spec:
  host: {{ .Values.publicSubdomain }}.upchieve.org
  prefix: /whiteboard/
  rewrite: /whiteboard/
  timeout_ms: 500000
  service: "{{ include "subway.fullname" . }}-socket.{{ .Release.Namespace }}:{{ .Values.httpPort }}"
  allow_upgrade:
    - websocket
  resolver: endpoint
  load_balancer:
    policy: ring_hash
    source_ip: true
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  subway-{{ .Release.Namespace }}-socket-mapping
  labels:
    {{- include "subway.labels" . | nindent 4 }}
spec:
  host: {{ .Values.publicSubdomain }}.upchieve.org
  prefix: /
  timeout_ms: 500000
  service: "{{ include "subway.fullname" . }}-socket-stable.{{ .Release.Namespace }}:{{ .Values.socketPort }}"
  query_parameters:
    transport: true
  allow_upgrade:
    - websocket
  resolver: endpoint
  load_balancer:
    policy: ring_hash
    source_ip: true
