---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  subway-{{ .Release.Namespace }}-api-mapping
  labels:
    {{- include "subway.labels" . | nindent 4 }}
spec:
  host: {{ .Values.publicSubdomain }}.upchieve.org
  prefix: /api/
  rewrite: /api/
  timeout_ms: 500000
  service: {{ include "subway.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.httpPort }}
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  subway-{{ .Release.Namespace }}-auth-mapping
  labels:
    {{- include "subway.labels" . | nindent 4 }}
spec:
  host: {{ .Values.publicSubdomain }}.upchieve.org
  prefix: /auth/
  rewrite: /auth/
  timeout_ms: 500000
  service: {{ include "subway.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.httpPort }}
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  subway-{{ .Release.Namespace }}-metrics-mapping
  labels:
    {{- include "subway.labels" . | nindent 4 }}
spec:
  host: {{ .Values.publicSubdomain }}.upchieve.org
  prefix: /metrics
  rewrite: /metrics
  timeout_ms: 500000
  service: {{ include "subway.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.httpPort }}
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  subway-{{ .Release.Namespace }}-api-public-mapping
  labels:
    {{- include "subway.labels" . | nindent 4 }}
spec:
  host: {{ .Values.publicSubdomain }}.upchieve.org
  prefix: /api-public/
  rewrite: /api-public/
  timeout_ms: 500000
  service: {{ include "subway.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.httpPort }}
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  subway-{{ .Release.Namespace }}-twiml-mapping
  labels:
    {{- include "subway.labels" . | nindent 4 }}
spec:
  host: {{ .Values.publicSubdomain }}.upchieve.org
  prefix: /twiml/
  rewrite: /twiml/
  timeout_ms: 500000
  service: {{ include "subway.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.httpPort }}
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  subway-{{ .Release.Namespace }}-setcookie-mapping
  labels:
    {{- include "subway.labels" . | nindent 4 }}
spec:
  host: {{ .Values.publicSubdomain }}.upchieve.org
  prefix: /setcookie
  rewrite: /setcookie
  timeout_ms: 500000
  service: {{ include "subway.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.httpPort }}
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  subway-{{ .Release.Namespace }}-whiteboard-reset-mapping
  labels:
    {{- include "subway.labels" . | nindent 4 }}
spec:
  host: {{ .Values.publicSubdomain }}.upchieve.org
  prefix: /whiteboard/reset/
  rewrite: /whiteboard/reset/
  timeout_ms: 500000
  service: {{ include "subway.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.httpPort }}
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  subway-{{ .Release.Namespace }}-whiteboard-mapping
  labels:
    {{- include "subway.labels" . | nindent 4 }}
spec:
  host: {{ .Values.publicSubdomain }}.upchieve.org
  prefix: /whiteboard/
  rewrite: /whiteboard/
  timeout_ms: 500000
  service: {{ include "subway.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.httpPort }}
  allow_upgrade:
    - websocket
  resolver: endpoint
  load_balancer:
    policy: ring_hash
    source_ip: true
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  subway-{{ .Release.Namespace }}-socket-mapping
  labels:
    {{- include "subway.labels" . | nindent 4 }}
spec:
  host: {{ .Values.publicSubdomain }}.upchieve.org
  prefix: /
  timeout_ms: 500000
  service: {{ include "subway.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.socketPort }}
  query_parameters:
    transport: true
  allow_upgrade:
    - websocket
  resolver: endpoint
  load_balancer:
    policy: ring_hash
    source_ip: true
