---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  subway-{{ .Release.Namespace }}-stable-mapping
  labels:
    {{- include "subway.labels" . | nindent 4 }}
spec:
  host: {{ .Values.publicSubdomain }}.upchieve.org
  prefix: /
  timeout_ms: 500000
  resolver: endpoint
  load_balancer:
    policy: least_request
  service: "{{ include "subway.fullname" . }}-stable.{{ .Release.Namespace }}:{{ .Values.httpPort }}"
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  subway-{{ .Release.Namespace }}-whiteboard-reset-stable-mapping
  labels:
    {{- include "subway.labels" . | nindent 4 }}
spec:
  host: {{ .Values.publicSubdomain }}.upchieve.org
  prefix: /whiteboard/reset/
  rewrite: /whiteboard/reset/
  timeout_ms: 500000
  resolver: endpoint
  load_balancer:
    policy: least_request
  service: "{{ include "subway.fullname" . }}-stable.{{ .Release.Namespace }}:{{ .Values.httpPort }}"
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  subway-{{ .Release.Namespace }}-whiteboard-stable-mapping
  labels:
    {{- include "subway.labels" . | nindent 4 }}
spec:
  host: {{ .Values.publicSubdomain }}.upchieve.org
  prefix: /whiteboard/
  rewrite: /whiteboard/
  timeout_ms: 500000
  service: "{{ include "subway.fullname" . }}-stable.{{ .Release.Namespace }}:{{ .Values.httpPort }}"
  allow_upgrade:
    - websocket
  resolver: endpoint
  load_balancer:
    policy: least_request
  keepalive:
    time: 7200
    interval: 75
    probes: 9
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  subway-{{ .Release.Namespace }}-socket-stable-mapping
  labels:
    {{- include "subway.labels" . | nindent 4 }}
spec:
  host: {{ .Values.publicSubdomain }}.upchieve.org
  prefix: /
  timeout_ms: 500000
  service: "{{ include "subway.fullname" . }}-stable.{{ .Release.Namespace }}:{{ .Values.socketPort }}"
  query_parameters:
    transport: true
  allow_upgrade:
    - websocket
  resolver: endpoint
  load_balancer:
    policy: least_request
  keepalive:
    time: 7200
    interval: 75
    probes: 9
