{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "subway.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      component: web
      {{- include "subway.selectorLabels" . | nindent 6 }}
{{- end }}
