apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "subway.fullname" . }}-socket
  labels:
  {{- include "subway.labels" . | nindent 4 }}
  {{- with .Values.ambassador.rollouts.annotations }}
  annotations:
  {{- toYaml . | nindent 4}}
  {{- end}}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: 1
  {{- end }}
  revisionHistoryLimit: 5
  strategy:
    canary:
      canaryService: {{ include "subway.fullname" . }}-socket-canary
      stableService: {{ include "subway.fullname" . }}-socket
      trafficRouting:
        ambassador:
          mappings:
            - subway-{{ .Release.Namespace }}-whiteboard-reset-stable-mapping
            - subway-{{ .Release.Namespace }}-whiteboard-stable-mapping
            - subway-{{ .Release.Namespace }}-socket-stable-mapping
      {{- with .Values.ambassador.rollouts.steps }}
      steps:
      {{- toYaml . | nindent 8}}
  {{- end}}
  selector:
    matchLabels:
      component: web
      traffic: socket
  {{- include "subway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        component: web
        traffic: socket
    {{- include "subway.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "subway.serviceAccountName" . }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.ambassador.rollouts.image.repository }}:{{ .Values.ambassador.rollouts.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command:
            - web
          env:
            - name: DOPPLER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: subway-{{ .Release.Namespace }}-doppler-token
                  key: DOPPLER_TOKEN
            - name: SUBWAY_VERSION
              value: {{ .Values.ambassador.rollouts.image.tag }}
          ports:
            - name: http
              containerPort: {{ .Values.httpPort }}
              protocol: TCP
            - name: socket
              containerPort: {{ .Values.socketPort }}
              protocol: TCP
          # Let the app start up, check every 6 seconds, 10 times
          # as soon as this comes back healthy k8s will move
          # to readiness and liveness probes. It has a minute to start.
          startupProbe:
            httpGet:
              path: /healthz
              port: http
            failureThreshold: 10
            periodSeconds: 6
            timeoutSeconds: 1
            successThreshold: 1
          # If the app fails a readiness check 2 times (20 seconds) in a row
          # k8s will stop sending traffic, but won't restart the
          # pod, to give it a chance to recover. Requests have 3
          # seconds to finish.
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 2
            timeoutSeconds: 3
          # If it fails this 8 more times than readiness (100 seconds) the pod
          # will get restarted. we're essentially giving it 15
          # seconds to recover before getting restarted. Requests
          # have 3 seconds to finish.
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 10
            timeoutSeconds: 3
            successThreshold: 1
          resources:
      {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: tmp
          emptyDir:
            medium: "Memory"
