apiVersion: apps/v1
kind: Rollout
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: subway-rollouts-test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: subway
    app.kubernetes.io/version: 0.0.1
    helm.sh/chart: subway-0.1.0
  name: subway-rollouts-test
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/instance: subway-rollouts-test
      app.kubernetes.io/name: subway
      component: web
  strategy:
    canary:
      steps:
      - setWeight: 1
      - pause:
          duration: 72
      - setWeight: 2
      - pause:
          duration: 72
      - setWeight: 3
      - pause:
          duration: 72
      - setWeight: 4
      - pause:
          duration: 72
      - setWeight: 5
      - pause:
          duration: 72
      - setWeight: 6
      - pause:
          duration: 72
      - setWeight: 7
      - pause:
          duration: 72
      - setWeight: 8
      - pause:
          duration: 72
      - setWeight: 9
      - pause:
          duration: 72
      - setWeight: 10
      - pause:
          duration: 72
      - setWeight: 11
      - pause:
          duration: 72
      - setWeight: 12
      - pause:
          duration: 72
      - setWeight: 13
      - pause:
          duration: 72
      - setWeight: 14
      - pause:
          duration: 72
      - setWeight: 15
      - pause:
          duration: 72
      - setWeight: 16
      - pause:
          duration: 72
      - setWeight: 17
      - pause:
          duration: 72
      - setWeight: 18
      - pause:
          duration: 72
      - setWeight: 19
      - pause:
          duration: 72
      - setWeight: 20
      - pause:
          duration: 72
      - setWeight: 21
      - pause:
          duration: 72
      - setWeight: 22
      - pause:
          duration: 72
      - setWeight: 23
      - pause:
          duration: 72
      - setWeight: 24
      - pause:
          duration: 72
      - setWeight: 25
      - pause:
          duration: 72
      - setWeight: 26
      - pause:
          duration: 72
      - setWeight: 27
      - pause:
          duration: 72
      - setWeight: 28
      - pause:
          duration: 72
      - setWeight: 29
      - pause:
          duration: 72
      - setWeight: 30
      - pause:
          duration: 72
      - setWeight: 31
      - pause:
          duration: 72
      - setWeight: 32
      - pause:
          duration: 72
      - setWeight: 33
      - pause:
          duration: 72
      - setWeight: 34
      - pause:
          duration: 72
      - setWeight: 35
      - pause:
          duration: 72
      - setWeight: 36
      - pause:
          duration: 72
      - setWeight: 37
      - pause:
          duration: 72
      - setWeight: 38
      - pause:
          duration: 72
      - setWeight: 39
      - pause:
          duration: 72
      - setWeight: 40
      - pause:
          duration: 72
      - setWeight: 41
      - pause:
          duration: 72
      - setWeight: 42
      - pause:
          duration: 72
      - setWeight: 43
      - pause:
          duration: 72
      - setWeight: 44
      - pause:
          duration: 72
      - setWeight: 45
      - pause:
          duration: 72
      - setWeight: 46
      - pause:
          duration: 72
      - setWeight: 47
      - pause:
          duration: 72
      - setWeight: 48
      - pause:
          duration: 72
      - setWeight: 49
      - pause:
          duration: 72
      - setWeight: 50
      - pause:
          duration: 72
      - setWeight: 51
      - pause:
          duration: 72
      - setWeight: 52
      - pause:
          duration: 72
      - setWeight: 53
      - pause:
          duration: 72
      - setWeight: 54
      - pause:
          duration: 72
      - setWeight: 55
      - pause:
          duration: 72
      - setWeight: 56
      - pause:
          duration: 72
      - setWeight: 57
      - pause:
          duration: 72
      - setWeight: 58
      - pause:
          duration: 72
      - setWeight: 59
      - pause:
          duration: 72
      - setWeight: 60
      - pause:
          duration: 72
      - setWeight: 61
      - pause:
          duration: 72
      - setWeight: 62
      - pause:
          duration: 72
      - setWeight: 63
      - pause:
          duration: 72
      - setWeight: 64
      - pause:
          duration: 72
      - setWeight: 65
      - pause:
          duration: 72
      - setWeight: 66
      - pause:
          duration: 72
      - setWeight: 67
      - pause:
          duration: 72
      - setWeight: 68
      - pause:
          duration: 72
      - setWeight: 69
      - pause:
          duration: 72
      - setWeight: 70
      - pause:
          duration: 72
      - setWeight: 71
      - pause:
          duration: 72
      - setWeight: 72
      - pause:
          duration: 72
      - setWeight: 73
      - pause:
          duration: 72
      - setWeight: 74
      - pause:
          duration: 72
      - setWeight: 75
      - pause:
          duration: 72
      - setWeight: 76
      - pause:
          duration: 72
      - setWeight: 77
      - pause:
          duration: 72
      - setWeight: 78
      - pause:
          duration: 72
      - setWeight: 79
      - pause:
          duration: 72
      - setWeight: 80
      - pause:
          duration: 72
      - setWeight: 81
      - pause:
          duration: 72
      - setWeight: 82
      - pause:
          duration: 72
      - setWeight: 83
      - pause:
          duration: 72
      - setWeight: 84
      - pause:
          duration: 72
      - setWeight: 85
      - pause:
          duration: 72
      - setWeight: 86
      - pause:
          duration: 72
      - setWeight: 87
      - pause:
          duration: 72
      - setWeight: 88
      - pause:
          duration: 72
      - setWeight: 89
      - pause:
          duration: 72
      - setWeight: 90
      - pause:
          duration: 72
      - setWeight: 91
      - pause:
          duration: 72
      - setWeight: 92
      - pause:
          duration: 72
      - setWeight: 93
      - pause:
          duration: 72
      - setWeight: 94
      - pause:
          duration: 72
      - setWeight: 95
      - pause:
          duration: 72
      - setWeight: 96
      - pause:
          duration: 72
      - setWeight: 97
      - pause:
          duration: 72
      - setWeight: 98
      - pause:
          duration: 72
      - setWeight: 99
      - pause:
          duration: 72
      - setWeight: 100
      - pause:
          duration: 72
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: subway-rollouts-test
        app.kubernetes.io/name: subway
        component: web
    spec:
      containers:
      - command:
        - web
        env:
        - name: DOPPLER_TOKEN
          valueFrom:
            secretKeyRef:
              key: DOPPLER_TOKEN
              name: subway-rollouts-test-doppler-token
        image: "1.0"
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        name: subway
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        - containerPort: 3001
          name: socket
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
        resources:
          limits:
            cpu: 250m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 150Mi
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      securityContext:
        fsGroup: 2000
      serviceAccountName: subway-rollouts-test
      volumes:
      - emptyDir:
          medium: Memory
        name: tmp
status:
  blueGreen: {}
  canary: {}
