apiVersion: v1
kind: Service
metadata:
  name: {{ include "high-line.fullname" . }}
  labels:
    {{- include "high-line.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.httpPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "high-line.selectorLabels" . | nindent 4 }}
